
version: '3.3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    env_file:
    - .env 
    ports:
      - '5432:5432'
    volumes: 
      - /var/lib/postgresql/
     
      
  python-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    links:
      - db
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db:
    driver: local

